Update path to templates in README
Current path doesn't include wasm_templates which results in errors:

```bash
⚠️   Favorite `https://github.com/tari-project/wasm-template.git` not found in config, using it as a git repository: https://github.com/tari-project/wasm-template.git
Error: not able to find subfolder 'nft' in source template
```

This change simply adds missing path element to make it work.